version: "3.8"

services:
  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: olist-airflow-webserver
    restart: unless-stopped
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"

      PROJECT_ROOT: /opt/project
      PYTHONUNBUFFERED: "1"

      # =========================
      # Supabase Postgres (fill these)
      # =========================
      SUPABASE_DB_HOST: "<SUPABASE_HOST>"
      SUPABASE_DB_NAME: "postgres"
      SUPABASE_DB_USER: "postgres"
      SUPABASE_DB_PASSWORD: "<SUPABASE_PASSWORD>"
      SUPABASE_DB_PORT: "5432"
      SUPABASE_DB_SSLMODE: "require"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/project
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: olist-airflow-scheduler
    restart: unless-stopped
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"

      PROJECT_ROOT: /opt/project
      PYTHONUNBUFFERED: "1"

      # =========================
      # Supabase Postgres 
      # =========================
      SUPABASE_DB_HOST: ${SUPABASE_DB_HOST}
      SUPABASE_DB_NAME: ${SUPABASE_DB_NAME}
      SUPABASE_DB_USER: ${SUPABASE_DB_USER}
      SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      SUPABASE_DB_PORT: ${SUPABASE_DB_PORT}
      SUPABASE_DB_SSLMODE: ${SUPABASE_DB_SSLMODE}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/project
      - airflow_logs:/opt/airflow/logs
    command: scheduler

  airflow-postgres:
    image: postgres:15
    container_name: olist-airflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data

volumes:
  airflow_logs:
  airflow_db:
