source:
  source_dir: data/raw/olist/incoming
  bronze_dir: data/bronze/olist_parquet
  file_format: csv
  write_format: parquet
  partition_by: batch_id
  write_mode: append

tables:
  - name: olist_orders_dataset
    file: olist_orders_dataset.csv
    timestamp_cols:
      - order_purchase_timestamp
      - order_approved_at
      - order_delivered_carrier_date
      - order_delivered_customer_date
      - order_estimated_delivery_date
    numeric_cols: []

  - name: olist_order_items_dataset
    file: olist_order_items_dataset.csv
    timestamp_cols:
      - shipping_limit_date
    numeric_cols:
      - price
      - freight_value

  - name: olist_products_dataset
    file: olist_products_dataset.csv
    timestamp_cols: []
    numeric_cols:
      - product_name_lenght
      - product_description_lenght
      - product_photos_qty
      - product_weight_g
      - product_length_cm
      - product_height_cm
      - product_width_cm

  - name: olist_customers_dataset
    file: olist_customers_dataset.csv
    timestamp_cols: []
    numeric_cols: []

  - name: olist_order_payments_dataset
    file: olist_order_payments_dataset.csv
    timestamp_cols: []
    numeric_cols:
      - payment_sequential
      - payment_installments
      - payment_value
